#if !defined(_TOCDAS_NAMES_H)

#define _TOCDAS_NAMES_H 

typedef struct {
  char * name ;
  int value ;
  char * comment ;
} msg_names_t ;

static msg_names_t ToCdasMsgNames[] = {
  {"M_READY", M_READY, NULL},
  {"M_RUN_START_ACK", M_RUN_START_ACK, NULL},
  {"M_RUN_PAUSE_ACK", M_RUN_PAUSE_ACK, NULL},
  {"M_RUN_CONTINUE_ACK", M_RUN_CONTINUE_ACK, NULL},
  {"M_RUN_STOP_ACK", M_RUN_STOP_ACK, NULL},
  {"M_T2_YES", M_T2_YES, NULL},
  {"M_T3_EVT", M_T3_EVT, NULL},
  {"M_T3_MUONS", M_T3_MUONS, NULL},
  {"M_CONFIG_SET_ACK", M_CONFIG_SET_ACK, NULL},
  {"M_MONIT_REQ_ACK", M_MONIT_REQ_ACK, NULL},
  {"M_MONIT_SEND", M_MONIT_SEND, NULL},
  {"M_CALIB_REQ_ACK", M_CALIB_REQ_ACK, NULL},
  {"M_CALIB_SEND", M_CALIB_SEND, NULL},
  {"M_BAD_SEQUENCE", M_BAD_SEQUENCE, NULL},
  {"M_BAD_VERSION", M_BAD_VERSION, NULL},
  {"M_MSG_ERROR", M_MSG_ERROR, NULL},
  {"M_DOWNLOAD_ACK", M_DOWNLOAD_ACK, NULL},
  {"M_SHELL_CMD_ACK", M_SHELL_CMD_ACK, NULL},
  {"M_MODULE2FLASH_ACK", M_MODULE2FLASH_ACK, NULL},
  {"M_UPLOAD_SEND", M_UPLOAD_SEND, NULL},
  {"M_SET_PARAM_ACK", M_SET_PARAM_ACK, NULL},
  {"M_GENERIC_STR", M_GENERIC_STR, NULL},
  {NULL, 0, NULL}
} ;

#endif
