#!/bin/sh

### BEGIN INIT INFO
# Provides:          candriver
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: candriver
# Description: Load canbus drivers and create can0 interface 
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Loading SJA1000 drivers"
		/root/scripts/startcanbus
		case "$?" in
			0) log_end_msg 0 ; exit 0 ;;
			1) log_warning_msg " Already loaded drivers" ; exit 0 ;;
			*) log_end_msg 1 ; exit ;;
		esac
		;;
	stop)
		log_daemon_msg "Unloading SJA1000 drivers"
		/root/scripts/stopcanbus
		case "$?" in
			0) log_end_msg 0 ; exit 0 ;;
			1) log_warning_msg " Drivers weren't loaded" ; exit 0 ;;
			*) log_end_msg 1 ; exit 1 ;;
		esac
		;;
restart|force-reload)
	log_daemon_msg " Reloading SJA1000 drivers"
	/root/scripts/startcanbus
	case "$?" in
	0|1)
		/root/scripts/startcanbus
		case "$?" in
			0) log_end_msg 0 ; exit 0 ;;
			1) log_failure_msg " Failed to reload, Old drivers running." ; exit 1 ;;
			*) log_failure_msg " Failed to reload." ; exit 1 ;;
		esac
		;;
	*)
		log_failure_msg " Couldn't stop drivers."
		exit 1
		;;
	esac
	;;
*)
	echo "Usage: /etc/init.d/candriver {start|stop|force-reload|restart}" >&2
	exit 1
	;;
esac
